export const Locators = {
    pageLogo: '#header-search > div > a > svg',
    basketIcon: '#basket',
    newsLetter: 'xpath=//*[@id="footer-container"]/footer/div[2]/div/form/div/div[1]/h5',
    subscribe: 'UButton__BtnPrimaryBgDefault-sc-1wh861e-1 jsdfVJ UNewsletter__StyledButton-sc-1952uhd-4 gxKYTx',
    changeLanguageBtn: '#footer-container > footer > div:nth-child(7) > div > div > div > a',
    italianLng: '#gatsby-focus-wrapper > main > div > div.UOffCanvasPanel__StyledRoot-sc-138g2ds-7.dkgrno > aside > div > div > div.UAccordion__StyledAccordionSection-sc-1cm8557-4.xLOBf > div.UAccordion__StyledContent-sc-1cm8557-0.esjuMM > div > div > ul > li:nth-child(4) > p > a',
    bikes: '//*[@id="header-search"]/div/div[1]/nav/ul/li[1]/a',
    plpCategories: '//*[@id="gatsby-focus-wrapper"]/main/div/main/div[2]/div/div[1]/div[1]/h4',
    plpComparison: '//*[@id="gatsby-focus-wrapper"]/main/div/main/div[2]/div/div[1]/div[2]/ul/li[1]/figure/div/div[3]/div/a',
    bikeClick: '#gatsby-focus-wrapper > main > div > main > div.UContainer__StyledContainer-sc-63nakj-0.dwTrKZ > div > div.URow__StyledRow-sc-1i2dmo4-0.jHpsTP > div.UCol__StyledCol-sc-i5z2xs-0.eQAcJx.ProductListing__StyledCol-sc-36ssj-7.hVAGyH > ul > li:nth-child(1) > figure > div > div.OProductListXL__StyledProductInner-sc-pncx7k-3.cmEmpu > div.OProductListXL__HeaderWrapper-sc-pncx7k-2.twtbd > a:nth-child(3) > figure > div > img',
    filterAsc: '//*[@id="gatsby-focus-wrapper"]/main/div/main/div[2]/div/div[1]/div[2]/div/nav/div/button[2]',
    filterDesc: '//*[@id="gatsby-focus-wrapper"]/main/div/main/div[2]/div/div[1]/div[2]/div/nav/div/button[3]',
    bikeName: '//*[@id="gatsby-focus-wrapper"]/main/div/main/div[3]/section/div[1]/div/div[2]/div[2]/div[1]/h1',
    bikeSizeS: '//*[@id="gatsby-focus-wrapper"]/main/div/main/div[3]/section/div[1]/div/div[2]/div[2]/div[2]/div[1]/div[2]/div[2]/button[2]/span',
    bikePrice: '//*[@id="gatsby-focus-wrapper"]/main/div/main/div[3]/section/div[1]/div/div[2]/div[2]/div[2]/div[2]/div/span',
    addToCart: '//*[@id="pdp-ctas"]/div[1]/button',
    addedToCart: '//*[@id="Road Rage EQ AL U GRN S"]/div[2]/div[1]/div/div',
}
